// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeyykA4wB3vfdd1bjxcBx-1UKqsToCruU',
    appId: '1:373048849271:web:5a37634b724b114f77e772',
    messagingSenderId: '373048849271',
    projectId: 'fcm-app-2cbb7',
    authDomain: 'fcm-app-2cbb7.firebaseapp.com',
    storageBucket: 'fcm-app-2cbb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Dd1kyjJQKQXEn_sGZqBMxJUxU_BPGV8',
    appId: '1:373048849271:android:87cad6f803ac011b77e772',
    messagingSenderId: '373048849271',
    projectId: 'fcm-app-2cbb7',
    storageBucket: 'fcm-app-2cbb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxcpH3ZAT4nR7mRfm2dc8DW5XADi1PgE',
    appId: '1:373048849271:ios:ebd4a5b0dda7e3a177e772',
    messagingSenderId: '373048849271',
    projectId: 'fcm-app-2cbb7',
    storageBucket: 'fcm-app-2cbb7.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxcpH3ZAT4nR7mRfm2dc8DW5XADi1PgE',
    appId: '1:373048849271:ios:ebd4a5b0dda7e3a177e772',
    messagingSenderId: '373048849271',
    projectId: 'fcm-app-2cbb7',
    storageBucket: 'fcm-app-2cbb7.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeyykA4wB3vfdd1bjxcBx-1UKqsToCruU',
    appId: '1:373048849271:web:0b04895f46f776bd77e772',
    messagingSenderId: '373048849271',
    projectId: 'fcm-app-2cbb7',
    authDomain: 'fcm-app-2cbb7.firebaseapp.com',
    storageBucket: 'fcm-app-2cbb7.firebasestorage.app',
  );
}
